[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "commercetools.pricingdiscount"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Vendor/Commercetools", "Area/E-Commerce", "Type/Connector"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-commercetools.pricingdiscount"

[build-options]
observabilityIncluded = true
