// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://api.us-central1.gcp.commercetools.com") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Query cart discounts
    #
    # + projectKey - `key` of the Project
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A paged list of cart discounts 
    remote isolated function listCartDiscounts(string projectKey, map<string|string[]> headers = {}, *ListCartDiscountsQueries queries) returns CartDiscountPagedQueryResponse|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/cart-discounts`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}, "sort": {style: FORM, explode: true}, "where": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create a cart discount
    #
    # + projectKey - `key` of the Project
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Cart discount draft to create 
    # + return - The created cart discount 
    remote isolated function createCartDiscount(string projectKey, CartDiscountDraft payload, map<string|string[]> headers = {}, *CreateCartDiscountQueries queries) returns CartDiscount|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/cart-discounts`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get a cart discount by key
    #
    # + projectKey - `key` of the Project
    # + 'key - User-defined unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The cart discount 
    remote isolated function getCartDiscountByKey(string projectKey, string 'key, map<string|string[]> headers = {}, *GetCartDiscountByKeyQueries queries) returns CartDiscount|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/cart-discounts/key=${getEncodedUri('key)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update a cart discount by key
    #
    # + projectKey - `key` of the Project
    # + 'key - User-defined unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Version and update actions for the cart discount 
    # + return - The cart discount 
    remote isolated function updateCartDiscountByKey(string projectKey, string 'key, CartDiscountUpdate payload, map<string|string[]> headers = {}, *UpdateCartDiscountByKeyQueries queries) returns CartDiscount|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/cart-discounts/key=${getEncodedUri('key)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete a cart discount by key
    #
    # + projectKey - `key` of the Project
    # + 'key - User-defined unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The cart discount 
    remote isolated function deleteCartDiscountByKey(string projectKey, string 'key, map<string|string[]> headers = {}, *DeleteCartDiscountByKeyQueries queries) returns CartDiscount|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/cart-discounts/key=${getEncodedUri('key)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Get a cart discount by ID
    #
    # + projectKey - `key` of the Project
    # + id - Unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The cart discount 
    remote isolated function getCartDiscountById(string projectKey, string id, map<string|string[]> headers = {}, *GetCartDiscountByIdQueries queries) returns CartDiscount|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/cart-discounts/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update a cart discount by ID
    #
    # + projectKey - `key` of the Project
    # + id - Unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Version and update actions for the cart discount 
    # + return - The cart discount 
    remote isolated function updateCartDiscountById(string projectKey, string id, CartDiscountUpdate payload, map<string|string[]> headers = {}, *UpdateCartDiscountByIdQueries queries) returns CartDiscount|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/cart-discounts/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete a cart discount by ID
    #
    # + projectKey - `key` of the Project
    # + id - Unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The cart discount 
    remote isolated function deleteCartDiscountById(string projectKey, string id, map<string|string[]> headers = {}, *DeleteCartDiscountByIdQueries queries) returns CartDiscount|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/cart-discounts/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Query discount codes
    #
    # + projectKey - `key` of the Project
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A paged list of discount codes 
    remote isolated function listDiscountCodes(string projectKey, map<string|string[]> headers = {}, *ListDiscountCodesQueries queries) returns DiscountCodePagedQueryResponse|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/discount-codes`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}, "sort": {style: FORM, explode: true}, "where": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create a discount code
    #
    # + projectKey - `key` of the Project
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Discount code draft to create 
    # + return - The created discount code 
    remote isolated function createDiscountCode(string projectKey, DiscountCodeDraft payload, map<string|string[]> headers = {}, *CreateDiscountCodeQueries queries) returns DiscountCode|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/discount-codes`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get a discount code by ID
    #
    # + projectKey - `key` of the Project
    # + id - Unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The discount code 
    remote isolated function getDiscountCodeById(string projectKey, string id, map<string|string[]> headers = {}, *GetDiscountCodeByIdQueries queries) returns DiscountCode|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/discount-codes/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update a discount code by ID
    #
    # + projectKey - `key` of the Project
    # + id - Unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Version and update actions for the discount code 
    # + return - The discount code 
    remote isolated function updateDiscountCodeById(string projectKey, string id, DiscountCodeUpdate payload, map<string|string[]> headers = {}, *UpdateDiscountCodeByIdQueries queries) returns DiscountCode|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/discount-codes/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete a discount code by ID
    #
    # + projectKey - `key` of the Project
    # + id - Unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The discount code 
    remote isolated function deleteDiscountCodeById(string projectKey, string id, map<string|string[]> headers = {}, *DeleteDiscountCodeByIdQueries queries) returns DiscountCode|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/discount-codes/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Query product discounts
    #
    # + projectKey - `key` of the Project
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A paged list of product discounts 
    remote isolated function listProductDiscounts(string projectKey, map<string|string[]> headers = {}, *ListProductDiscountsQueries queries) returns ProductDiscountPagedQueryResponse|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/product-discounts`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}, "sort": {style: FORM, explode: true}, "where": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create a product discount
    #
    # + projectKey - `key` of the Project
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Product discount draft to create 
    # + return - The created product discount 
    remote isolated function createProductDiscount(string projectKey, ProductDiscountDraft payload, map<string|string[]> headers = {}, *CreateProductDiscountQueries queries) returns ProductDiscount|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/product-discounts`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get a product discount by key
    #
    # + projectKey - `key` of the Project
    # + 'key - User-defined unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The product discount 
    remote isolated function getProductDiscountByKey(string projectKey, string 'key, map<string|string[]> headers = {}, *GetProductDiscountByKeyQueries queries) returns ProductDiscount|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/product-discounts/key=${getEncodedUri('key)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update a product discount by key
    #
    # + projectKey - `key` of the Project
    # + 'key - User-defined unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Version and update actions for the product discount 
    # + return - The product discount 
    remote isolated function updateProductDiscountByKey(string projectKey, string 'key, ProductDiscountUpdate payload, map<string|string[]> headers = {}, *UpdateProductDiscountByKeyQueries queries) returns ProductDiscount|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/product-discounts/key=${getEncodedUri('key)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete a product discount by key
    #
    # + projectKey - `key` of the Project
    # + 'key - User-defined unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The product discount 
    remote isolated function deleteProductDiscountByKey(string projectKey, string 'key, map<string|string[]> headers = {}, *DeleteProductDiscountByKeyQueries queries) returns ProductDiscount|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/product-discounts/key=${getEncodedUri('key)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Get the product discount matching a product price
    #
    # + projectKey - `key` of the Project
    # + headers - Headers to be sent with the request 
    # + payload - Product and price to match against product discounts 
    # + return - The product discount 
    remote isolated function getMatchingProductDiscount(string projectKey, ProductDiscountMatchQuery payload, map<string|string[]> headers = {}) returns ProductDiscount|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/product-discounts/matching`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get a product discount by ID
    #
    # + projectKey - `key` of the Project
    # + id - Unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The product discount 
    remote isolated function getProductDiscountById(string projectKey, string id, map<string|string[]> headers = {}, *GetProductDiscountByIdQueries queries) returns ProductDiscount|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/product-discounts/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update a product discount by ID
    #
    # + projectKey - `key` of the Project
    # + id - Unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Version and update actions for the product discount 
    # + return - The product discount 
    remote isolated function updateProductDiscountById(string projectKey, string id, ProductDiscountUpdate payload, map<string|string[]> headers = {}, *UpdateProductDiscountByIdQueries queries) returns ProductDiscount|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/product-discounts/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete a product discount by ID
    #
    # + projectKey - `key` of the Project
    # + id - Unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The product discount 
    remote isolated function deleteProductDiscountById(string projectKey, string id, map<string|string[]> headers = {}, *DeleteProductDiscountByIdQueries queries) returns ProductDiscount|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/product-discounts/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Query tax categories
    #
    # + projectKey - `key` of the Project
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A paged list of tax categories 
    remote isolated function listTaxCategories(string projectKey, map<string|string[]> headers = {}, *ListTaxCategoriesQueries queries) returns TaxCategoryPagedQueryResponse|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/tax-categories`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}, "sort": {style: FORM, explode: true}, "where": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create a tax category
    #
    # + projectKey - `key` of the Project
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Tax category draft to create 
    # + return - The created tax category 
    remote isolated function createTaxCategory(string projectKey, TaxCategoryDraft payload, map<string|string[]> headers = {}, *CreateTaxCategoryQueries queries) returns TaxCategory|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/tax-categories`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get a tax category by key
    #
    # + projectKey - `key` of the Project
    # + 'key - User-defined unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The tax category 
    remote isolated function getTaxCategoryByKey(string projectKey, string 'key, map<string|string[]> headers = {}, *GetTaxCategoryByKeyQueries queries) returns TaxCategory|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/tax-categories/key=${getEncodedUri('key)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update a tax category by key
    #
    # + projectKey - `key` of the Project
    # + 'key - User-defined unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Version and update actions for the tax category 
    # + return - The tax category 
    remote isolated function updateTaxCategoryByKey(string projectKey, string 'key, TaxCategoryUpdate payload, map<string|string[]> headers = {}, *UpdateTaxCategoryByKeyQueries queries) returns TaxCategory|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/tax-categories/key=${getEncodedUri('key)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete a tax category by key
    #
    # + projectKey - `key` of the Project
    # + 'key - User-defined unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The tax category 
    remote isolated function deleteTaxCategoryByKey(string projectKey, string 'key, map<string|string[]> headers = {}, *DeleteTaxCategoryByKeyQueries queries) returns TaxCategory|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/tax-categories/key=${getEncodedUri('key)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Get a tax category by ID
    #
    # + projectKey - `key` of the Project
    # + id - Unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The tax category 
    remote isolated function getTaxCategoryById(string projectKey, string id, map<string|string[]> headers = {}, *GetTaxCategoryByIdQueries queries) returns TaxCategory|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/tax-categories/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update a tax category by ID
    #
    # + projectKey - `key` of the Project
    # + id - Unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Version and update actions for the tax category 
    # + return - The tax category 
    remote isolated function updateTaxCategoryById(string projectKey, string id, TaxCategoryUpdate payload, map<string|string[]> headers = {}, *UpdateTaxCategoryByIdQueries queries) returns TaxCategory|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/tax-categories/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete a tax category by ID
    #
    # + projectKey - `key` of the Project
    # + id - Unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The tax category 
    remote isolated function deleteTaxCategoryById(string projectKey, string id, map<string|string[]> headers = {}, *DeleteTaxCategoryByIdQueries queries) returns TaxCategory|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/tax-categories/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->delete(resourcePath, headers = headers);
    }
}
