// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

public type StoreKeyReference record {
    *KeyReference;
    ReferenceTypeId typeId;
    string 'key;
};

public type RecurringOrderScope record {
    string 'type;
};

# Represents the Queries record for the operation: updateProductDiscountByKey
public type UpdateProductDiscountByKeyQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
};

public type DiscountCodeUpdateAction record {
    string action;
};

public type Address record {
    *BaseAddress;
    CountryCode country?;
    string lastName?;
    string city?;
    string postalCode?;
    string title?;
    string building?;
    string streetName?;
    string company?;
    string id?;
    string state?;
    string department?;
    string fax?;
    string 'key?;
    string email?;
    string pOBox?;
    string streetNumber?;
    CustomFields custom?;
    string mobile?;
    string externalId?;
    string additionalAddressInfo?;
    string firstName?;
    string phone?;
    string additionalStreetInfo?;
    string salutation?;
    string region?;
    string apartment?;
};

public type Customer record {
    *BaseResource;
    string lastName?;
    Address[] addresses;
    string lastModifiedAt;
    string companyName?;
    string vatId?;
    string title?;
    Locale locale?;
    string[] shippingAddressIds;
    boolean isEmailVerified;
    string createdAt;
    string password?;
    string id;
    AuthenticationMode authenticationMode;
    string 'key?;
    string email;
    CustomerGroupReference customerGroup?;
    StoreKeyReference[] stores;
    LastModifiedBy lastModifiedBy?;
    CustomFields custom?;
    string externalId?;
    string dateOfBirth?;
    CustomerGroupAssignment[] customerGroupAssignments;
    string customerNumber?;
    string defaultShippingAddressId?;
    string[] billingAddressIds;
    int version;
    string defaultBillingAddressId?;
    string firstName?;
    CreatedBy createdBy?;
    string middleName?;
    string salutation?;
};

public type ProductDiscountPagedQueryResponse record {
    int total?;
    int offset;
    int 'limit;
    int count;
    ProductDiscount[] results;
};

public type CustomerGroupAssignment record {
    CustomerGroupReference customerGroup;
};

public type CurrencyCode string;

public type ResourceIdentifier record {
    ReferenceTypeId typeId;
    string id?;
    string 'key?;
};

public type TaxCategoryPagedQueryResponse record {
    int total?;
    int offset;
    int 'limit;
    int count;
    TaxCategory[] results;
};

public type ChannelRoleEnum "InventorySupply"|"ProductDistribution"|"OrderExport"|"OrderImport"|"Primary";

public type ProductDiscountMatchQuery record {
    string productId;
    QueryPrice price;
    int:Signed32 variantId;
    boolean staged;
};

public type ResourceTypeId "address"|"asset"|"approval-flow"|"approval-rule"|"associate-role"|"business-unit"|"cart-discount"|"category"|"channel"|"customer"|"customer-group"|"custom-line-item"|"discount-code"|"inventory-entry"|"line-item"|"order"|"order-edit"|"order-delivery"|"order-parcel"|"order-return-item"|"payment"|"payment-interface-interaction"|"payment-method"|"payment-method-info"|"product-price"|"product-selection"|"product-tailoring"|"quote"|"reservation"|"review"|"recurring-order"|"shipping"|"shipping-method"|"shopping-list"|"shopping-list-text-line-item"|"standalone-price"|"store"|"transaction";

public type CartDiscountValueDraft record {
    string 'type;
};

public type ProductDiscountDraft record {
    string predicate;
    string sortOrder;
    LocalizedString name;
    LocalizedString description?;
    string validUntil?;
    string validFrom?;
    boolean isActive;
    ProductDiscountValueDraft value;
    string 'key?;
};

# Represents the Queries record for the operation: listTaxCategories
public type ListTaxCategoriesQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
    # Number of results to skip, for paging. Default 0, maximum 10000
    int offset?;
    # Whether to calculate and return `total` in the response. Default `true`
    boolean withTotal?;
    # Maximum number of results to return. Default 20, maximum 500
    int 'limit?;
    # Query predicate that filters the results. Can be repeated
    string[] 'where?;
    # Sort expression, such as `createdAt desc`. Can be repeated
    string[] sort?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    OAuth2ClientCredentialsGrantConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

public type ProductDiscountValue record {
    string 'type;
};

# Represents the Queries record for the operation: listDiscountCodes
public type ListDiscountCodesQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
    # Number of results to skip, for paging. Default 0, maximum 10000
    int offset?;
    # Whether to calculate and return `total` in the response. Default `true`
    boolean withTotal?;
    # Maximum number of results to return. Default 20, maximum 500
    int 'limit?;
    # Query predicate that filters the results. Can be repeated
    string[] 'where?;
    # Sort expression, such as `createdAt desc`. Can be repeated
    string[] sort?;
};

# Represents the Queries record for the operation: listProductDiscounts
public type ListProductDiscountsQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
    # Number of results to skip, for paging. Default 0, maximum 10000
    int offset?;
    # Whether to calculate and return `total` in the response. Default `true`
    boolean withTotal?;
    # Maximum number of results to return. Default 20, maximum 500
    int 'limit?;
    # Query predicate that filters the results. Can be repeated
    string[] 'where?;
    # Sort expression, such as `createdAt desc`. Can be repeated
    string[] sort?;
};

public type CreatedBy record {
    *ClientLogging;
    string anonymousId?;
    string clientId?;
    string externalUserId?;
    Attribution attributedTo?;
    CustomerReference associate?;
    CustomerReference customer?;
};

public type ProductDiscountValueDraft record {
    string 'type;
};

public type TaxCategoryUpdate record {
    int version;
    TaxCategoryUpdateAction[] actions;
};

public type AuthenticationMode "Password"|"ExternalAuth";

public type CustomerReference record {
    *Reference;
    Customer obj?;
    ReferenceTypeId typeId;
    string id;
};

public type TaxCategoryDraft record {
    TaxRateDraft[] rates?;
    string name;
    string description?;
    string 'key?;
};

# Represents the Queries record for the operation: updateTaxCategoryByKey
public type UpdateTaxCategoryByKeyQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
};

# Represents the Queries record for the operation: getDiscountCodeById
public type GetDiscountCodeByIdQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
};

# Represents the Queries record for the operation: getTaxCategoryById
public type GetTaxCategoryByIdQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
};

public type LastModifiedBy record {
    *ClientLogging;
    string anonymousId?;
    string clientId?;
    string externalUserId?;
    Attribution attributedTo?;
    CustomerReference associate?;
    CustomerReference customer?;
};

# Represents the Queries record for the operation: deleteCartDiscountByKey
public type DeleteCartDiscountByKeyQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
    # Expected current version of the resource, for optimistic concurrency control
    int version;
};

# Represents the Queries record for the operation: createProductDiscount
public type CreateProductDiscountQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
};

public type StoreResourceIdentifier record {
    *ResourceIdentifier;
    ReferenceTypeId typeId?;
    string id?;
    string 'key?;
};

# Represents the Queries record for the operation: getTaxCategoryByKey
public type GetTaxCategoryByKeyQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
};

public type CartDiscountValue record {
    string 'type;
};

public type DiscountGroupResourceIdentifier record {
    *ResourceIdentifier;
    ReferenceTypeId typeId?;
    string id?;
    string 'key?;
};

# Represents the Queries record for the operation: updateCartDiscountByKey
public type UpdateCartDiscountByKeyQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
};

# Represents the Queries record for the operation: listCartDiscounts
public type ListCartDiscountsQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
    # Number of results to skip, for paging. Default 0, maximum 10000
    int offset?;
    # Whether to calculate and return `total` in the response. Default `true`
    boolean withTotal?;
    # Maximum number of results to return. Default 20, maximum 500
    int 'limit?;
    # Query predicate that filters the results. Can be repeated
    string[] 'where?;
    # Sort expression, such as `createdAt desc`. Can be repeated
    string[] sort?;
};

public type CustomerGroupReference record {
    *Reference;
    CustomerGroup obj?;
    ReferenceTypeId typeId;
    string id;
};

public type TypeReference record {
    *Reference;
    Type obj?;
    ReferenceTypeId typeId;
    string id;
};

public type CartDiscount record {
    *BaseResource;
    boolean requiresDiscountCode;
    string lastModifiedAt;
    Reference[] references;
    string cartPredicate;
    StoreKeyReference[] stores;
    LastModifiedBy lastModifiedBy?;
    CustomFields custom?;
    LocalizedString description?;
    string validFrom?;
    boolean isActive;
    RecurringOrderScope recurringOrderScope;
    int version;
    CartDiscountTarget target?;
    string createdAt;
    CreatedBy createdBy?;
    string sortOrder;
    StackingMode stackingMode;
    LocalizedString name;
    string validUntil?;
    string id;
    CartDiscountValue value;
    string 'key?;
    DiscountGroupReference discountGroup?;
};

public type CartDiscountPagedQueryResponse record {
    int total?;
    int offset;
    int 'limit;
    int count;
    CartDiscount[] results;
};

public type FieldContainer record {|
    string...;
|};

public type TypeTextInputHint "SingleLine"|"MultiLine";

public type CartDiscountResourceIdentifier record {
    *ResourceIdentifier;
    ReferenceTypeId typeId?;
    string id?;
    string 'key?;
};

public type Reference record {
    ReferenceTypeId typeId;
    string id;
};

# Represents the Queries record for the operation: deleteDiscountCodeById
public type DeleteDiscountCodeByIdQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
    # Expected current version of the resource, for optimistic concurrency control
    int version;
    # Whether to erase all personal data related to the resource. Default `false`
    boolean dataErasure?;
};

public type TaxCategory record {
    *BaseResource;
    string createdAt;
    string lastModifiedAt;
    CreatedBy createdBy?;
    LastModifiedBy lastModifiedBy?;
    TaxRate[] rates;
    string name;
    string description?;
    string id;
    int version;
    string 'key?;
};

# Represents the Queries record for the operation: deleteCartDiscountById
public type DeleteCartDiscountByIdQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
    # Expected current version of the resource, for optimistic concurrency control
    int version;
};

public type ReferenceTypeId "approval-flow"|"approval-rule"|"associate-role"|"attribute-group"|"business-unit"|"cart"|"cart-discount"|"category"|"channel"|"customer"|"customer-email-token"|"customer-group"|"customer-password-token"|"direct-discount"|"discount-code"|"discount-group"|"extension"|"inventory-entry"|"key-value-document"|"mcp-server"|"order"|"order-edit"|"payment-method"|"payment"|"product"|"product-discount"|"product-price"|"product-selection"|"product-tailoring"|"product-type"|"quote"|"quote-request"|"recurrence-policy"|"recurring-order"|"reservation"|"review"|"shipping-method"|"shopping-list"|"staged-quote"|"standalone-price"|"state"|"store"|"subscription"|"tax-category"|"type"|"variant"|"zone";

public type TaxRateDraft record {
    CountryCode country;
    decimal amount?;
    boolean includedInPrice;
    string name;
    string state?;
    string 'key?;
    SubRate[] subRates?;
    TaxRoundingTarget taxRoundingTarget?;
};

public type DiscountCode record {
    *BaseResource;
    CartDiscountReference[] cartDiscounts;
    int applicationVersion?;
    string lastModifiedAt;
    string code;
    Reference[] references;
    string cartPredicate?;
    StoreKeyReference[] stores;
    LastModifiedBy lastModifiedBy?;
    CustomFields custom?;
    LocalizedString description?;
    string[] groups;
    string validFrom?;
    boolean isActive;
    int version;
    int maxApplications?;
    string createdAt;
    CreatedBy createdBy?;
    LocalizedString name?;
    string validUntil?;
    string id;
    int maxApplicationsPerCustomer?;
    string 'key?;
};

public type DiscountedPriceDraft record {
    ProductDiscountReference discount;
    Money value;
};

# Represents the Queries record for the operation: updateProductDiscountById
public type UpdateProductDiscountByIdQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
};

# Represents the Queries record for the operation: updateTaxCategoryById
public type UpdateTaxCategoryByIdQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
};

# Represents the Queries record for the operation: getProductDiscountById
public type GetProductDiscountByIdQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
};

public type DiscountCodePagedQueryResponse record {
    int total?;
    int offset;
    int 'limit;
    int count;
    DiscountCode[] results;
};

public type ProductDiscountUpdateAction record {
    string action;
};

public type Type record {
    *BaseResource;
    string createdAt;
    string lastModifiedAt;
    CreatedBy createdBy?;
    LastModifiedBy lastModifiedBy?;
    LocalizedString name;
    LocalizedString description?;
    FieldDefinition[] fieldDefinitions;
    string id;
    int version;
    string 'key;
    ResourceTypeId[] resourceTypeIds;
};

public type QueryPrice record {
    DiscountedPriceDraft discounted?;
    CountryCode country?;
    PriceTierDraft[] tiers?;
    CustomerGroupReference customerGroup?;
    CustomFields custom?;
    ChannelReference channel?;
    string validUntil?;
    string id?;
    string validFrom?;
    Money value;
};

public type CartDiscountTarget record {
    string 'type;
};

# Represents the Queries record for the operation: getCartDiscountById
public type GetCartDiscountByIdQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
};

# Represents the Queries record for the operation: deleteProductDiscountByKey
public type DeleteProductDiscountByKeyQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
    # Expected current version of the resource, for optimistic concurrency control
    int version;
};

# Represents the Queries record for the operation: createCartDiscount
public type CreateCartDiscountQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
};

public type CustomFieldsDraft record {
    TypeResourceIdentifier 'type;
    FieldContainer fields?;
};

public type Locale string;

# OAuth2 Client Credentials Grant Configs
public type OAuth2ClientCredentialsGrantConfig record {|
    *http:OAuth2ClientCredentialsGrantConfig;
    # Token URL
    string tokenUrl = "https://auth.us-central1.gcp.commercetools.com/oauth/token";
|};

public type TaxRoundingTarget "Net"|"Tax";

public type KeyReference record {
    ReferenceTypeId typeId;
    string 'key;
};

public type FieldDefinition record {
    string name;
    TypeTextInputHint inputHint?;
    LocalizedString label;
    FieldType 'type;
    boolean required;
};

# Represents the Queries record for the operation: deleteTaxCategoryById
public type DeleteTaxCategoryByIdQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
    # Expected current version of the resource, for optimistic concurrency control
    int version;
};

# Represents the Queries record for the operation: createDiscountCode
public type CreateDiscountCodeQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
};

public type ProductDiscountReference record {
    *Reference;
    ProductDiscount obj?;
    ReferenceTypeId typeId;
    string id;
};

public type CartDiscountUpdate record {
    int version;
    CartDiscountUpdateAction[] actions;
};

public type CartDiscountDraft record {
    boolean requiresDiscountCode?;
    string cartPredicate;
    StoreResourceIdentifier[] stores?;
    CustomFieldsDraft custom?;
    LocalizedString description?;
    string validFrom?;
    boolean isActive?;
    RecurringOrderScopeDraft recurringOrderScope?;
    CartDiscountTarget target?;
    string sortOrder?;
    StackingMode stackingMode?;
    LocalizedString name;
    string validUntil?;
    CartDiscountValueDraft value;
    string 'key?;
    DiscountGroupResourceIdentifier discountGroup?;
};

public type PriceTierDraft record {
    int minimumQuantity;
    Money value;
};

public type CustomerGroup record {
    *BaseResource;
    string createdAt;
    string lastModifiedAt;
    CreatedBy createdBy?;
    LastModifiedBy lastModifiedBy?;
    CustomFields custom?;
    string name;
    string id;
    int version;
    string 'key?;
};

# Represents the Queries record for the operation: getCartDiscountByKey
public type GetCartDiscountByKeyQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
};

public type Channel record {
    *BaseResource;
    string lastModifiedAt;
    Address address?;
    LastModifiedBy lastModifiedBy?;
    ChannelRoleEnum[] roles;
    CustomFields custom?;
    LocalizedString description?;
    int version;
    string createdAt;
    CreatedBy createdBy?;
    GeoJson geoLocation?;
    LocalizedString name?;
    string id;
    string 'key;
    ReviewRatingStatistics reviewRatingStatistics?;
};

public type StackingMode "Stacking"|"StopAfterThisDiscount";

public type ProductDiscountUpdate record {
    int version;
    ProductDiscountUpdateAction[] actions;
};

public type ProductDiscount record {
    *BaseResource;
    string lastModifiedAt;
    Reference[] references;
    LastModifiedBy lastModifiedBy?;
    LocalizedString description?;
    string validFrom?;
    boolean isActive;
    int version;
    string createdAt;
    string predicate;
    CreatedBy createdBy?;
    string sortOrder;
    LocalizedString name;
    string validUntil?;
    string id;
    ProductDiscountValue value;
    string 'key?;
};

# Represents the Queries record for the operation: deleteTaxCategoryByKey
public type DeleteTaxCategoryByKeyQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
    # Expected current version of the resource, for optimistic concurrency control
    int version;
};

public type Attribution record {
    string clientId?;
    AttributionSource 'source;
};

public type CustomFields record {
    TypeReference 'type;
    FieldContainer fields;
};

public type DiscountCodeUpdate record {
    int version;
    DiscountCodeUpdateAction[] actions;
};

public type RecurringOrderScopeDraft record {
    string 'type;
};

# Represents the Queries record for the operation: deleteProductDiscountById
public type DeleteProductDiscountByIdQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
    # Expected current version of the resource, for optimistic concurrency control
    int version;
};

public type GeoJson record {
    string 'type;
};

public type TypeResourceIdentifier record {
    *ResourceIdentifier;
    ReferenceTypeId typeId?;
    string id?;
    string 'key?;
};

# Represents the Queries record for the operation: createTaxCategory
public type CreateTaxCategoryQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
};

public type LocalizedString record {|
    string...;
|};

public type DiscountCodeDraft record {
    CartDiscountResourceIdentifier[] cartDiscounts;
    string code;
    string cartPredicate?;
    CustomFieldsDraft custom?;
    LocalizedString description?;
    string[] groups?;
    string validFrom?;
    boolean isActive?;
    int maxApplications?;
    LocalizedString name?;
    string validUntil?;
    int maxApplicationsPerCustomer?;
    string 'key?;
};

public type Money record {
    int centAmount;
    CurrencyCode currencyCode;
};

public type CartDiscountUpdateAction record {
    string action;
};

public type AttributionSource "Import"|"Export";

# Represents the Queries record for the operation: updateCartDiscountById
public type UpdateCartDiscountByIdQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
};

public type ChannelReference record {
    *Reference;
    Channel obj?;
    ReferenceTypeId typeId;
    string id;
};

public type TaxRate record {
    CountryCode country;
    decimal amount;
    boolean includedInPrice;
    string name;
    string id?;
    string state?;
    string 'key?;
    SubRate[] subRates?;
    TaxRoundingTarget taxRoundingTarget?;
};

public type CountryCode string;

public type CartDiscountReference record {
    *Reference;
    CartDiscount obj?;
    ReferenceTypeId typeId;
    string id;
};

public type DiscountGroupReference record {
    *Reference;
    DiscountGroup obj?;
    ReferenceTypeId typeId;
    string id;
};

# Represents the Queries record for the operation: updateDiscountCodeById
public type UpdateDiscountCodeByIdQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
};

public type TaxCategoryUpdateAction record {
    string action;
};

public type ClientLogging record {
    string anonymousId?;
    string clientId?;
    string externalUserId?;
    CustomerReference associate?;
    CustomerReference customer?;
};

public type BaseResource record {
    string createdAt;
    string lastModifiedAt;
    string id;
    int version;
};

public type BaseAddress record {
    CountryCode country;
    string lastName?;
    string city?;
    string postalCode?;
    string title?;
    string building?;
    string streetName?;
    string company?;
    string id?;
    string state?;
    string department?;
    string fax?;
    string 'key?;
    string email?;
    string pOBox?;
    string streetNumber?;
    string mobile?;
    string externalId?;
    string additionalAddressInfo?;
    string firstName?;
    string phone?;
    string additionalStreetInfo?;
    string salutation?;
    string region?;
    string apartment?;
};

public type FieldType record {
    string name;
};

public type ReviewRatingStatistics record {
    decimal highestRating;
    decimal averageRating;
    int:Signed32 count;
    decimal lowestRating;
    record {} ratingsDistribution;
};

public type SubRate record {
    decimal amount;
    string name;
};

# Represents the Queries record for the operation: getProductDiscountByKey
public type GetProductDiscountByKeyQueries record {
    # Reference path to expand in the response. Can be repeated
    string[] expand?;
};

public type DiscountGroup record {
    *BaseResource;
    string createdAt;
    string lastModifiedAt;
    CreatedBy createdBy?;
    string sortOrder;
    LastModifiedBy lastModifiedBy?;
    LocalizedString name?;
    LocalizedString description?;
    string id;
    boolean isActive;
    int version;
    string 'key;
};
